gen_data_dir: "/mnt/data/jpombal/wmt24-chat-translation/instructions/no_context_empty_sys"
eval_data_dir: "/mnt/data/jpombal/wmt24-chat-translation/raw_data"
gen_output_dir: "/mnt/data/jpombal/wmt24-chat-translation/generations/no_context_empty_sys"
eval_output_dir: "/mnt/data/jpombal/wmt24-chat-translation/evaluations/no_context_empty_sys"
tasks: 
  - name: mt
    subtasks:
      bcontrast_test.en-de:
      bcontrast_test.de-en:
    metrics:
      chrf:
      bleu:
      comet:
      comet_kiwi:
models:
  - name: TowerChat-7B
    type: vllm
    arguments:
      model_dir: Unbabel/TowerInstruct-v0.2-w-chat-mt-data
      n_gpus: 1
      max_tokens: 1024
      run_async: True
      batch_size: -1
      strip: False