gen_data_dir: "/mnt/data/jpombal/wmt24-chat-translation/instructions/english_context_empty_sys"
eval_data_dir: "/mnt/data/jpombal/wmt24-chat-translation/raw_data"
gen_output_dir: "/mnt/data/jpombal/wmt24-chat-translation/generations/english_context_empty_sys"
eval_output_dir: "/mnt/data/jpombal/wmt24-chat-translation/evaluations/english_context_empty_sys"
tasks: 
  - name: mt
    subtasks:
      wmt24_chat_test.en-pt-br:
      wmt24_chat_test.pt-br-en:
      wmt24_chat_test.en-de:
      wmt24_chat_test.de-en:
      wmt24_chat_test.en-fr:
      wmt24_chat_test.fr-en:
      wmt24_chat_test.en-nl:
      wmt24_chat_test.nl-en:
      wmt24_chat_test.en-ko:
      wmt24_chat_test.ko-en:
      bcontrast_test.de-en:
      bcontrast_test.en-de:
    metrics:
      comet:
      chrf:
models:
  - name: TowerInstruct-7B-w-chat-empty-sys
    type: vllm
    arguments:
      model_dir: Unbabel/TowerInstruct-WMT24-Chat-7B
      n_gpus: 1
      max_tokens: 1024
      run_async: True
      batch_size: -1
      strip: False