#
##en-de
#python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-de/greedy-7b-ft-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-de/greedy-7b-ft-w-context_fp16_tok_370/test --data_path alti_prep_data/test_en-de_datadf.json --model_version greedy-7b-ft-w-context --language en-de  --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-de/greedy-7b-ft-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-de/greedy-7b-ft-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_en-de_datadf.json --model_version greedy-7b-ft-wo-context --language en-de --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-de/greedy-7b-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-de/greedy-7b-w-context_fp16_tok_370/test --data_path alti_prep_data/test_en-de_datadf.json --model_version greedy-7b-w-context --language en-de  --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-de/greedy-7b-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-de/greedy-7b-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_en-de_datadf.json --model_version greedy-7b-wo-context --language en-de  --normalized
#
##de-en
#python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/de-en/greedy-7b-ft-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/de-en/greedy-7b-ft-w-context_fp16_tok_370/test --data_path alti_prep_data/test_de-en_datadf.json --model_version greedy-7b-ft-w-context --language de-en  --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/de-en/greedy-7b-ft-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/de-en/greedy-7b-ft-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_de-en_datadf.json --model_version greedy-7b-ft-wo-context --language de-en  --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/de-en/greedy-7b-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/de-en/greedy-7b-w-context_fp16_tok_370/test --data_path alti_prep_data/test_de-en_datadf.json --model_version greedy-7b-w-context --language de-en  --normalized
#python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/de-en/greedy-7b-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/de-en/greedy-7b-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_de-en_datadf.json --model_version greedy-7b-wo-context --language de-en  --normalized


#en-ko
python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-ko/greedy-7b-ft-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-ko/greedy-7b-ft-w-context_fp16_tok_370/test --data_path alti_prep_data/test_en-ko_datadf.json --model_version greedy-7b-ft-w-context --language en-ko  --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-ko/greedy-7b-ft-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-ko/greedy-7b-ft-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_en-ko_datadf.json --model_version greedy-7b-ft-wo-context --language en-ko --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-ko/greedy-7b-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-ko/greedy-7b-w-context_fp16_tok_370/test --data_path alti_prep_data/test_en-ko_datadf.json --model_version greedy-7b-w-context --language en-ko  --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/en-ko/greedy-7b-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/en-ko/greedy-7b-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_en-ko_datadf.json --model_version greedy-7b-wo-context --language en-ko  --normalized

#ko-en
python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/ko-en/greedy-7b-ft-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/ko-en/greedy-7b-ft-w-context_fp16_tok_370/test --data_path alti_prep_data/test_ko-en_datadf.json --model_version greedy-7b-ft-w-context --language ko-en  --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-chat --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/ko-en/greedy-7b-ft-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/ko-en/greedy-7b-ft-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_ko-en_datadf.json --model_version greedy-7b-ft-wo-context --language ko-en  --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/ko-en/greedy-7b-w-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/ko-en/greedy-7b-w-context_fp16_tok_370/test --data_path alti_prep_data/test_ko-en_datadf.json --model_version greedy-7b-w-context --language ko-en  --normalized
python alti_analysis/aggregate_contributions.py --model_name tower-instruct --model_prec fp16 --contributions_out_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/ko-en/greedy-7b-wo-context_fp16_tok_370 --save_folder /mnt/scratch-artemis/manos/data/wmt24_chat_mt/alti_contributions/norm_aggregated/ko-en/greedy-7b-wo-context_fp16_tok_370/test --data_path alti_prep_data/test_ko-en_datadf.json --model_version greedy-7b-wo-context --language ko-en  --normalized

